mypy passed

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -61,14 +61,16 @@ jobs:
 
     - name: Debug
       run: |
-        echo "Contents of pyproject.toml:"
-        cat pyproject.toml
-        echo "Checking if [tool.flake8] exists:"
-        grep -A 3 "\[tool.flake8\]" pyproject.toml || echo "[tool.flake8] not found"
-        echo "Flake8 and dependencies versions:"
-        poetry run pip show flake8 pycodestyle pyflakes tomli
-        echo "Checking pyproject.toml encoding:"
-        file pyproject.toml
+        echo "Current directory:"
+        pwd
+        echo "List files:"
+        ls -la
+        echo "Contents of .mypy.ini:"
+        cat .mypy.ini || echo ".mypy.ini not found"
+        echo "Versions:"
+        poetry run pip show mypy torch
+        echo "File encodings:"
+        file pyproject.toml .mypy.ini
 
     - name: Run Black (Check only)
       run: poetry run black --check src/
@@ -77,7 +79,7 @@ jobs:
       run: poetry run flake8 src/
 
     - name: Run Mypy
-      run: poetry run mypy src/ --python-version=3.12 --ignore-missing-imports --disable-error-code=no-untyped-def,type-arg,no-untyped-call
+      run: poetry run mypy src/ --config-file=./.mypy.ini
 
     - name: Run Minimal Functional Test
       run: >-
